name: checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
           submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        working-directory: ./
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Run lint
        run: npm run lint
      - name: Run tsc
        run: npm run clean && npm run tsc

