name: Deploy docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install deps
        run: npm i

        # CI should be able to commit built files to the gh-pages branch
        # It's impossible if they're ignored
      - name: Update .gitignore
        run: sed -ie '/__REMOVE_BELOW_LINE__/,+1 d' .gitignore

      - name: Build
        run: npm run build
      - name: Build static
        run: npm run build:static
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: .
